# -*- coding: utf-8 -*-
UNIDADES={
"EMC":[("I","Avaliação inicial do doente adulto e registos de enfermagem",1,10,
 "Âmbito e limites de competência do Técnico de Enfermagem. Admissão e acolhimento. Exame físico céfalo-caudal. Sinais vitais e sinais de alerta precoce. Processo do doente, notas de evolução, folha terapêutica e passagem de turno estruturada."),
("II","Biossegurança, prevenção e controlo de infecção e tratamento de feridas",2,8,
 "Infecções associadas aos cuidados de saúde e cadeia de transmissão. Precauções-padrão e higienização das mãos. Equipamento de protecção individual e isolamentos. Gestão de resíduos hospitalares. Assepsia, desinfecção e esterilização. Campo estéril e penso simples. Feridas, cicatrização e prevenção de úlceras de pressão."),
("III","Enfermagem ao doente respiratório e cardiovascular",3,7,
 "Pneumonia, asma e doença pulmonar obstrutiva crónica. Posicionamento e cinesiterapia respiratória. Oxigenoterapia, aerossolterapia e aspiração de secreções. Hipertensão arterial e insuficiência cardíaca. Síndromes coronárias agudas. Balanço hídrico."),
("IV","Enfermagem ao doente digestivo, renal e endócrino",4,7,
 "Hemorragia digestiva e hepatopatias. Sonda nasogástrica e alimentação entérica. Insuficiência renal e balanço hídrico. Cateterismo vesical. Diabetes mellitus, glicemia capilar e insulinoterapia. Pé diabético."),
("V","Doenças infecciosas prevalentes no adulto",5,4,
 "Malária e malária grave: sinais de gravidade, teste rápido de diagnóstico e cuidados. Tuberculose: isolamento respiratório e adesão terapêutica. VIH/SIDA. Doença diarreica e reidratação no adulto."),
("VI","Doente crítico, choque e enfermagem perioperatória",6,8,
 "Choque: tipos, reconhecimento, posicionamento e fluidoterapia. Preparação pré-operatória e lista de verificação de segurança cirúrgica. Cuidados pós-operatórios. Deiscência, infecção do local cirúrgico e prevenção de tromboembolismo."),
("VII","Integração em casos clínicos do adulto",7,7,
 "Casos que cruzam disciplinas: malária grave com desidratação; adulto politraumatizado em internamento; doente crónico com hipertensão e diabetes. Continuidade de cuidados, referência e contra-referência."),
("VIII","Revisão, consolidação e avaliação final",8,8,
 "Revisão integrada das unidades. Resolução de situações clínicas. Avaliação prática final em estações e avaliação final teórico-prática.")],

"UEPS":[("I","Organização da urgência, triagem e abordagem primária",1,6,
 "Organização e fluxos do serviço de urgência. Âmbito de actuação do Técnico de Enfermagem. Triagem e classificação de risco. Abordagem primária ABCDE e reavaliação. Registo do episódio de urgência e comunicação estruturada."),
("II","Via aérea, ventilação e Suporte Básico de Vida com DAE",2,8,
 "Permeabilização da via aérea, posição lateral de segurança, aspiração e tubo orofaríngeo. Ventilação com insuflador manual e máscara. Reconhecimento da paragem cardiorrespiratória e cadeia de sobrevivência. Suporte Básico de Vida no adulto com desfibrilhador automático externo."),
("III","Hemorragia, choque e acessos venosos periféricos",3,5,
 "Controlo de hemorragia externa: compressão directa, penso compressivo e torniquete. Choque: reconhecimento precoce, posicionamento e fluidoterapia inicial. Punção venosa periférica em contexto de urgência."),
("IV","Emergência traumatológica",4,5,
 "Avaliação primária e secundária da vítima de trauma. Traumatismos por acidente de viação. Imobilização de fracturas com talas e ligaduras. Estabilização cervical e rolamento em bloco. Mobilização e transporte em maca e plano duro."),
("V","Queimaduras, intoxicações e mordeduras",5,4,
 "Queimaduras: extensão, profundidade, arrefecimento, penso e reposição de fluidos. Intoxicações e envenenamentos. Mordeduras de serpente, picadas e mordeduras de cão. Profilaxia do tétano e da raiva."),
("VI","Emergências clínicas",6,8,
 "Convulsão e estado de mal convulsivo. Alteração do estado de consciência. Malária grave e desidratação grave em urgência. Hipoglicemia e cetoacidose diabética. Anafilaxia, crise asmática e insuficiência respiratória aguda."),
("VII","Emergência colectiva e integração",7,5,
 "Princípios de triagem em situação de multivítimas. Carro de urgência: composição, verificação diária e reposição. Simulação integrada com triagem, estabilização e referência."),
("VIII","Revisão, consolidação e avaliação prática final",8,8,
 "Revisão dos algoritmos de suporte básico de vida e de abordagem ao trauma. Treino final com correcção individual. Avaliação prática final em estações.")],

"SMON":[("I","Saúde sexual e reprodutiva e planeamento familiar",1,7,
 "Conceitos de saúde sexual e reprodutiva. Direitos da mulher, ética e âmbito de actuação. Anatomofisiologia do aparelho reprodutor feminino e ciclo menstrual. Métodos contraceptivos, aconselhamento, administração e seguimento."),
("II","Vigilância pré-natal",2,8,
 "Diagnóstico de gravidez e modificações fisiológicas. Cálculo da idade gestacional e da data provável do parto. Consulta pré-natal, exames de rotina e cartão da grávida. Altura uterina, manobras de Leopold e auscultação do foco fetal. Nutrição, suplementação, vacinação antitetânica e educação para a saúde."),
("III","Gravidez de risco e prevenção da transmissão vertical",3,8,
 "Anemia na gravidez: rastreio e prevenção. Malária na gravidez: tratamento preventivo intermitente e rede mosquiteira. Sífilis. Prevenção da transmissão vertical do VIH e da hepatite B: aconselhamento, testagem, adesão e seguimento."),
("IV","Trabalho de parto e partograma",4,4,
 "Fisiologia e períodos do trabalho de parto. Mecanismo do parto. Admissão da parturiente. Partograma: preenchimento, linha de alerta, linha de acção e decisão de referência."),
("V","Assistência ao parto e dequitadura",5,5,
 "Preparação do material e do campo. Apoio e posições da parturiente. Assistência ao parto normal em modelo: protecção do períneo e clampagem do cordão. Terceiro período: manejo activo da dequitadura e revisão da placenta."),
("VI","Emergências obstétricas",6,7,
 "Pré-eclâmpsia e eclâmpsia: pesquisa de proteinúria, vigilância e conduta de emergência. Hemorragia pós-parto: massagem uterina e compressão bimanual. Uterotónicos sob supervisão. Sépsis materna e infecção puerperal."),
("VII","Enfermagem neonatal",7,8,
 "Cuidados imediatos ao recém-nascido, secagem, contacto pele a pele e índice de Apgar. Reanimação neonatal básica com ventilação por máscara. Aleitamento materno e pega correcta. Sépsis neonatal, icterícia, recém-nascido de baixo peso e método canguru."),
("VIII","Revisão, consolidação e avaliação final",8,8,
 "Revisão integrada com interpretação de partogramas e simulação de emergência obstétrica. Avaliação final em estações.")],

"EPSC":[("I","Crescimento, desenvolvimento e avaliação da criança",1,5,
 "Princípios da enfermagem pediátrica e direitos da criança. Comunicação com a criança e a família. Marcos do desenvolvimento e curvas de crescimento. Avaliação antropométrica. Sinais vitais por faixa etária e sinais gerais de perigo."),
("II","Nutrição infantil e malnutrição aguda",2,8,
 "Aleitamento exclusivo e diversificação alimentar. Erros alimentares frequentes. Rastreio da malnutrição aguda por perímetro braquial e pesquisa de edema bilateral. Classificação e cuidados na malnutrição aguda grave e moderada. Alimentos terapêuticos prontos a usar. Educação nutricional e vigilância do ganho ponderal."),
("III","Abordagem integrada das doenças da infância e imunização",3,8,
 "Abordagem integrada: avaliar, classificar, tratar e referir. Programa Alargado de Vacinação: calendário, cadeia de frio e técnica de administração. Registo vacinal, eventos adversos pós-vacinação e recuperação de faltosos."),
("IV","Doença diarreica e desidratação",4,4,
 "Avaliação do grau de desidratação. Planos de tratamento A, B e C. Terapia de reidratação oral: preparação da solução, administração e educação do cuidador."),
("V","Infecções respiratórias agudas e malária na criança",5,7,
 "Pneumonia: contagem da frequência respiratória, tiragem e classificação. Bronquiolite, asma e laringite. Nebulização e oxigenoterapia pediátrica. Malária e malária grave na criança: sinais de gravidade e teste rápido de diagnóstico."),
("VI","Drepanocitose, febre e emergências pediátricas",6,5,
 "Drepanocitose: crise vaso-oclusiva, hidratação, controlo da dor e prevenção de complicações. Febre na criança e convulsão febril. Doenças exantemáticas e medidas de isolamento."),
("VII","Terapêutica pediátrica e integração",7,8,
 "Cálculo de doses por peso e dupla verificação. Administração por via oral, intramuscular e endovenosa. Punção venosa periférica e fluidoterapia com cálculo do ritmo de gotejo. Casos integrados. Avaliação e controlo da dor. Sinais de maus-tratos e dever de comunicação."),
("VIII","Revisão, consolidação e avaliação final",8,8,
 "Revisão integrada com estudo de casos. Avaliação final prática em estações e componente escrita.")],
}

LISTAS={
"EMC":[("EMC-01","Higienização das mãos e colocação e remoção de EPI",
 ["Retira adornos das mãos e antebraços","Executa a higienização nos cinco momentos definidos","Cumpre a duração e a técnica de fricção em todas as faces das mãos","Selecciona o EPI adequado ao tipo de precaução","Coloca o EPI pela sequência correcta","Remove o EPI sem contaminar a pele e a farda","Descarta cada peça no contentor da categoria certa","Higieniza as mãos após a remoção"]),
("EMC-02","Técnica de penso simples em ferida limpa",
 ["Informa o doente e obtém colaboração","Reúne o material e verifica prazos e integridade das embalagens","Higieniza as mãos e calça luvas","Remove o penso anterior sem traccionar a pele","Observa e descreve a ferida, o exsudado e a pele circundante","Abre o campo estéril sem o contaminar","Executa a limpeza do centro para a periferia, com uma compressa por passagem","Aplica o penso, fixa e regista a observação e a hora"]),
("EMC-03","Montagem e início de oxigenoterapia",
 ["Confere a indicação e o débito prescrito","Verifica a fonte de oxigénio e o débitómetro","Coloca água no humidificador quando indicado","Selecciona o dispositivo adequado ao débito","Adapta o dispositivo ao doente sem pontos de pressão","Confirma o débito efectivo no débitómetro","Verifica a ausência de fontes de ignição no espaço","Avalia a resposta com oximetria e regista"]),
("EMC-04","Cateterismo vesical em simulador",
 ["Confirma a indicação e informa o doente","Assegura privacidade e posicionamento","Higieniza as mãos e prepara campo estéril","Executa a antissepsia do meato pela sequência correcta","Mantém a técnica estéril durante toda a introdução","Introduz a sonda até ao retorno de urina antes de insuflar o balão","Insufla o balão com o volume indicado e conecta o saco em circuito fechado","Fixa a sonda, posiciona o saco abaixo do nível da bexiga e regista"]),
("EMC-05","Colocação de sonda nasogástrica",
 ["Confirma a indicação e informa o doente","Posiciona o doente em Fowler","Mede o comprimento a introduzir e marca a sonda","Lubrifica a sonda e introduz sem forçar","Interrompe e retira perante tosse, cianose ou resistência","Confirma o posicionamento pelo método instituído no serviço","Fixa a sonda sem pressão sobre a narina","Regista o calibre, o comprimento, o método de confirmação e a tolerância"])],

"UEPS":[("UEPS-01","Triagem e atribuição de prioridade",
 ["Assegura a segurança do local e a sua própria protecção","Colhe o motivo de vinda em menos de um minuto","Avalia via aérea, respiração, circulação e estado de consciência","Mede os sinais vitais essenciais","Identifica os sinais de alarme presentes","Atribui a prioridade justificando o critério","Comunica a prioridade à equipa de forma estruturada","Regista a hora de triagem e a prioridade atribuída"]),
("UEPS-02","Abordagem primária ABCDE",
 ["Garante a segurança do local antes de abordar a vítima","A — verifica e permeabiliza a via aérea com controlo cervical quando indicado","B — avalia a respiração, a frequência e a expansão torácica e oxigena","C — avalia o pulso, a perfusão e controla hemorragia visível","D — avalia o estado de consciência e a glicemia capilar","E — expõe a vítima e previne a hipotermia","Reavalia a sequência após cada intervenção","Regista os achados e comunica na transferência"]),
("UEPS-03","Suporte Básico de Vida no adulto com DAE",
 ["Confirma a segurança do local","Avalia a resposta e a respiração em menos de dez segundos","Pede ajuda e o desfibrilhador","Posiciona as mãos no centro do tórax","Comprime a 5–6 cm de profundidade, a 100–120 por minuto","Permite a reexpansão completa entre compressões","Mantém a relação de 30 compressões para 2 ventilações","Aplica o DAE, afasta todos antes do choque e retoma de imediato as compressões"]),
("UEPS-04","Controlo de hemorragia externa",
 ["Calça luvas antes do contacto","Localiza o ponto de hemorragia expondo a região","Aplica compressão directa firme e mantida","Aplica penso compressivo sem remover as compressas embebidas","Eleva o membro quando não há suspeita de fractura","Aplica torniquete quando a compressão falha, acima da lesão","Regista a hora de aplicação do torniquete de forma visível","Vigia a perfusão distal e os sinais de choque"]),
("UEPS-05","Estabilização cervical e transferência para plano duro",
 ["Mantém estabilização manual da cabeça desde a abordagem","Selecciona e aplica o colar cervical do tamanho correcto","Reúne equipa suficiente e distribui funções","Coordena o rolamento em bloco com comando único","Mantém o alinhamento da cabeça, pescoço e tronco","Coloca o plano duro e reposiciona a vítima ao centro","Fixa a vítima com cintos e imobilizadores de cabeça","Reavalia a via aérea, a respiração e a perfusão após a transferência"])],

"SMON":[("SMON-01","Consulta pré-natal",
 ["Acolhe a grávida e assegura privacidade","Confirma a identificação e revê o cartão da grávida","Colhe a história e calcula a idade gestacional e a data provável do parto","Mede o peso, a tensão arterial e pesquisa edemas","Executa a pesquisa de proteinúria quando indicada","Verifica o estado vacinal e a suplementação","Educa sobre sinais de perigo e sobre o plano de parto","Regista todos os achados no cartão e no processo"]),
("SMON-02","Manobras de Leopold e auscultação do foco fetal",
 ["Explica o procedimento e obtém consentimento","Assegura o esvaziamento vesical e posiciona a grávida","Aquece as mãos antes do contacto","Executa as quatro manobras pela ordem correcta","Determina a situação, a apresentação e a posição","Mede a altura uterina com fita métrica","Localiza e ausculta o foco fetal durante um minuto completo","Regista a frequência cardíaca fetal e a altura uterina"]),
("SMON-03","Preenchimento e interpretação do partograma",
 ["Regista a identificação e a hora de admissão","Regista a dilatação cervical no momento correcto do gráfico","Regista a descida da apresentação","Regista a frequência cardíaca fetal nos intervalos definidos","Regista as contracções em frequência e duração","Regista os sinais vitais maternos","Identifica o cruzamento da linha de alerta e da linha de acção","Comunica o desvio e desencadeia a referência em tempo útil"]),
("SMON-04","Assistência ao parto normal em modelo",
 ["Reúne e confere o material antes do período expulsivo","Higieniza as mãos e coloca EPI completo","Prepara o campo estéril","Apoia o períneo e controla a saída da cabeça","Verifica a presença de circular do cordão","Auxilia a saída dos ombros sem tracção excessiva","Clampa e corta o cordão no tempo indicado","Coloca o recém-nascido em contacto pele a pele e regista a hora do parto"]),
("SMON-05","Reanimação neonatal básica",
 ["Prepara e testa o material antes do parto","Seca o recém-nascido e retira os panos húmidos","Assegura a termorregulação","Posiciona a cabeça em posição neutra e permeabiliza a via aérea","Avalia a respiração e a frequência cardíaca em menos de trinta segundos","Inicia ventilação com máscara no primeiro minuto quando indicado","Assegura a selagem da máscara e a expansão torácica visível","Reavalia a cada trinta segundos e chama ajuda diferenciada"])],

"EPSC":[("EPSC-01","Avaliação antropométrica da criança",
 ["Verifica a calibração da balança antes da pesagem","Pesa a criança com o mínimo de roupa e sem calçado","Mede o comprimento ou a estatura conforme a idade","Mede o perímetro cefálico no ponto correcto","Mede o perímetro braquial no ponto médio do braço esquerdo","Pesquisa edema bilateral com pressão mantida","Marca os valores nas curvas de crescimento","Interpreta a curva e comunica o resultado ao cuidador"]),
("EPSC-02","Contagem da frequência respiratória e classificação de pneumonia",
 ["Assegura que a criança está calma antes de contar","Conta os movimentos respiratórios durante um minuto completo","Aplica o limiar correspondente à faixa etária","Observa a presença de tiragem subcostal","Pesquisa estridor em repouso","Pesquisa os sinais gerais de perigo","Classifica a situação segundo a abordagem integrada","Decide entre tratar e referir e regista a decisão"]),
("EPSC-03","Avaliação da desidratação e escolha do plano de tratamento",
 ["Avalia o estado geral e a reactividade","Observa os olhos e a presença de lágrimas","Pesquisa o sinal da prega cutânea","Avalia a sede oferecendo líquido","Classifica o grau de desidratação","Selecciona o plano A, B ou C de acordo com a classificação","Calcula o volume a administrar segundo o peso","Educa o cuidador e regista o plano instituído"]),
("EPSC-04","Cálculo de dose por peso e dupla verificação",
 ["Confirma o peso actual da criança","Confirma o fármaco, a dose por quilograma e a via","Executa o cálculo por escrito","Confere a concentração da apresentação disponível","Calcula o volume a administrar","Submete o cálculo a segunda verificação por outro profissional","Confirma os cinco certos antes da administração","Regista a dose, a via e a hora imediatamente após administrar"]),
("EPSC-05","Administração de vacina e cadeia de frio",
 ["Verifica e regista a temperatura do frigorífico","Confirma o prazo de validade e o aspecto do frasco","Confirma a vacina, a dose, a via e o local segundo o calendário","Prepara a vacina com técnica asséptica","Posiciona e imobiliza a criança em segurança","Administra pela via e ângulo correctos","Descarta o material perfurante no contentor próprio","Regista no boletim e agenda a dose seguinte"])],
}
