# -*- coding: utf-8 -*-
FUND={
"EMC":"O internamento de adultos concentra a maior parte da actividade assistencial das unidades sanitárias e é o contexto onde o Técnico de Enfermagem exerce a sua função de forma mais continuada. Concluídas as disciplinas de Técnicas de Enfermagem, Farmacologia, Anatomia e Doenças Correntes, o formando domina o gesto isolado e reconhece a doença; falta-lhe integrar ambos na gestão de um doente concreto ao longo de um turno. Esta disciplina faz essa passagem: organiza o cuidado por aparelhos e sistemas, articula a técnica com o raciocínio clínico e instala uma cultura de biossegurança e de segurança do doente que atravessa todos os procedimentos.",
"UEPS":"A capacidade de reconhecer precocemente a deterioração clínica e de agir nos primeiros minutos determina o prognóstico de forma mais decisiva do que qualquer intervenção posterior. Com tempos de transporte prolongados e recursos diferenciados desigualmente distribuídos, o Técnico de Enfermagem é frequentemente o primeiro profissional junto da vítima. A disciplina instala um método único de abordagem, treinado até à automatização, e reserva a maior parte do seu tempo à repetição deliberada em manequim e em cenário simulado, porque em emergência a competência que não foi treinada não está disponível.",
"SMON":"A mortalidade materna e neonatal responde de forma directa à competência de quem acompanha a mulher na consulta pré-natal, no trabalho de parto e nas primeiras horas de vida do recém-nascido. Grande parte das mortes evitáveis resulta de sinais de alerta não reconhecidos ou reconhecidos tarde. A disciplina prepara o formando para vigiar com método, registar com rigor, reconhecer precocemente a complicação e referir em tempo útil, dominando as manobras de primeira linha que não podem esperar pela chegada do pessoal diferenciado.",
"EPSC":"A criança não é um adulto de menor dimensão: a dose calcula-se, o sinal vital muda com a idade, a desidratação instala-se em horas e o quadro respiratório agrava-se sem aviso. A abordagem integrada das doenças da infância, a vigilância nutricional e a imunização concentram grande parte do impacto alcançável em saúde infantil e são precisamente as áreas onde o Técnico de Enfermagem intervém com maior frequência. A disciplina organiza esse conjunto em torno de três competências centrais: avaliar correctamente, classificar com critério e decidir se a criança fica, é tratada ou é referida.",
}
PRE={
"EMC":"Técnicas de Enfermagem — técnica asséptica, sinais vitais, administração de terapêutica por via oral, intramuscular e endovenosa. Farmacologia — cálculo de doses, vias de administração e efeitos adversos. Anatomia — aparelhos cardiovascular, respiratório, digestivo, renal e endócrino. Doenças Correntes — quadros clínicos do adulto. Mobilizados apenas como revisão breve ligada a conteúdo novo, até ao limite de 10 % da carga da disciplina.",
"UEPS":"Técnicas de Enfermagem — posicionamentos, punção venosa periférica e administração de terapêutica. Farmacologia — fármacos de urgência e vias de administração. Anatomia — via aérea, tórax, coluna vertebral e sistema osteoarticular. Doenças Correntes — quadros que evoluem para emergência. Limite de 10 % da carga da disciplina.",
"SMON":"Anatomia — aparelho reprodutor feminino e bacia obstétrica. Farmacologia — uterotónicos, sulfato de magnésio e antirretrovirais, na perspectiva da vigilância e não da prescrição. Técnicas de Enfermagem — assepsia, administração de terapêutica e sinais vitais. Doenças Correntes — anemia, malária, sífilis e VIH. Limite de 10 % da carga da disciplina.",
"EPSC":"Anatomia — particularidades anatomofisiológicas da criança. Farmacologia — formas farmacêuticas pediátricas e cálculo de doses. Técnicas de Enfermagem — punção venosa, administração de terapêutica e sinais vitais. Doenças Correntes — malária, doença diarreica e infecções respiratórias. Limite de 10 % da carga da disciplina.",
}
OBJG={
"EMC":"Capacitar o formando para prestar cuidados de enfermagem seguros, sistematizados e humanizados ao doente adulto em contexto de internamento médico e cirúrgico, aplicando os princípios de biossegurança, de prevenção e controlo de infecção e de segurança do doente em todos os procedimentos, e documentando a sua intervenção de modo a assegurar a continuidade do cuidado.",
"UEPS":"Capacitar o formando para reconhecer, priorizar e intervir de forma imediata, metódica e segura perante situações de urgência e emergência, executando as manobras de suporte básico de vida e de primeiros socorros do seu âmbito de competência e assegurando a referência adequada da vítima.",
"SMON":"Capacitar o formando para acompanhar a mulher ao longo do ciclo gravídico-puerperal e o recém-nascido nas primeiras horas de vida, executando a vigilância pré-natal, colaborando na assistência ao parto normal, reconhecendo precocemente as complicações obstétricas e neonatais e actuando com as manobras de primeira linha e a referência devida.",
"EPSC":"Capacitar o formando para avaliar, classificar e cuidar da criança, aplicando a abordagem integrada das doenças da infância, executando com segurança os procedimentos e a terapêutica pediátrica e promovendo a nutrição, a imunização e a protecção da criança.",
}
OBJE={
"EMC":["Executar a admissão e a avaliação inicial do doente adulto, incluindo o exame físico céfalo-caudal.",
"Identificar precocemente os sinais de deterioração clínica e comunicá-los à equipa em formato estruturado.",
"Aplicar as precauções-padrão, os isolamentos e as regras de gestão de resíduos em todos os cuidados prestados.",
"Executar a técnica de penso e as medidas de prevenção de úlceras de pressão.",
"Executar oxigenoterapia, aerossolterapia, aspiração de secreções, cateterismo vesical e colocação de sonda nasogástrica.",
"Prestar cuidados de enfermagem ao doente respiratório, cardiovascular, digestivo, renal e endócrino.",
"Distinguir os sinais de gravidade da malária, da tuberculose e da doença diarreica no adulto e desencadear a referência.",
"Preparar o doente para a cirurgia e prestar cuidados pós-operatórios, identificando as complicações mais frequentes.",
"Elaborar registos de enfermagem completos, legíveis e cronologicamente correctos.",
"Justificar a decisão de referência e de contra-referência perante uma situação clínica concreta."],
"UEPS":["Descrever a organização do serviço de urgência e delimitar o âmbito da sua própria actuação.",
"Aplicar a abordagem primária ABCDE de forma sistemática e reavaliar a vítima em intervalos definidos.",
"Classificar vítimas por prioridade, justificando o critério aplicado.",
"Executar Suporte Básico de Vida no adulto com qualidade verificável e operar o desfibrilhador automático externo em segurança.",
"Executar a permeabilização da via aérea e a ventilação com insuflador manual e máscara.",
"Controlar hemorragias externas por compressão directa, penso compressivo e torniquete.",
"Imobilizar fracturas e a coluna cervical e transferir a vítima com técnica segura.",
"Executar os primeiros cuidados em queimaduras, intoxicações, mordeduras e picadas.",
"Reconhecer a convulsão, a anafilaxia, a hipoglicemia e a malária grave e actuar de imediato.",
"Verificar e repor o carro de urgência e registar o episódio."],
"SMON":["Executar o aconselhamento em planeamento familiar e administrar os métodos contraceptivos do seu âmbito.",
"Executar a consulta pré-natal, preencher o cartão da grávida e calcular a idade gestacional e a data provável do parto.",
"Executar as manobras de Leopold, medir a altura uterina e auscultar o foco fetal.",
"Identificar precocemente os sinais de pré-eclâmpsia, de hemorragia e de infecção e desencadear a referência.",
"Preencher e interpretar o partograma, distinguindo o cruzamento da linha de alerta e da linha de acção.",
"Colaborar na assistência ao parto normal e executar o manejo activo do terceiro período sob supervisão.",
"Executar as manobras de primeira linha na hemorragia pós-parto.",
"Executar os cuidados imediatos ao recém-nascido e a reanimação neonatal básica.",
"Apoiar o estabelecimento do aleitamento materno e resolver as dificuldades mais frequentes.",
"Aplicar as medidas de prevenção da transmissão vertical do VIH, da sífilis e da hepatite B."],
"EPSC":["Medir e interpretar os parâmetros antropométricos e marcá-los nas curvas de crescimento.",
"Medir e interpretar os sinais vitais pediátricos de acordo com a faixa etária.",
"Identificar os sinais gerais de perigo e decidir sobre a referência imediata.",
"Classificar a malnutrição aguda e acompanhar a reabilitação nutricional.",
"Administrar vacinas com técnica correcta, assegurando a cadeia de frio e completando o registo.",
"Classificar a pneumonia pela contagem da frequência respiratória e pela presença de tiragem.",
"Avaliar o grau de desidratação e aplicar os planos de tratamento A, B e C.",
"Calcular doses pediátricas por peso e aplicar a regra da dupla verificação.",
"Executar punção venosa periférica e calcular o ritmo de gotejo da fluidoterapia.",
"Reconhecer os sinais de maus-tratos e de negligência e cumprir o dever de comunicação."],
}
COMP={
"EMC":(["Distingue os quadros clínicos do adulto que exigem vigilância acrescida.","Interpreta os sinais vitais e o balanço hídrico no contexto do doente.","Fundamenta a escolha do dispositivo e da técnica em cada procedimento."],
["Executa com destreza e assepsia os procedimentos invasivos do seu âmbito.","Organiza o turno por prioridades para um grupo de doentes.","Documenta a intervenção de forma que outro profissional continue o cuidado sem perda de informação."],
["Protege-se a si, ao doente e à equipa de forma sistemática.","Comunica com o doente e a família em linguagem compreensível e respeitosa.","Reconhece e declara os limites da sua competência."]),
"UEPS":(["Reconhece o padrão de gravidade a partir de poucos dados e em pouco tempo.","Selecciona a prioridade correcta e justifica-a.","Antecipa a evolução previsível da vítima."],
["Executa as manobras de suporte de vida com cadência e profundidade correctas.","Imobiliza, mobiliza e transporta a vítima sem agravar a lesão.","Prepara e verifica o material de emergência."],
["Mantém o método sob pressão de tempo e em ambiente adverso.","Assume e cede funções com clareza dentro da equipa.","Assegura permanentemente a segurança do local, da vítima e do socorrista."]),
"SMON":(["Interpreta o partograma e reconhece o desvio da normalidade.","Distingue a gravidez de baixo risco da gravidez de risco.","Relaciona os sinais maternos e fetais com a decisão de referir."],
["Executa a vigilância pré-natal completa e regista-a no cartão.","Executa as manobras salvadoras de primeira linha na hemorragia pós-parto e na reanimação neonatal.","Colabora na assistência ao parto preservando a assepsia e o períneo."],
["Respeita a dignidade, a intimidade e o contexto cultural da mulher.","Aconselha sem julgar e confirma a compreensão da informação.","Reconhece o momento de chamar ajuda diferenciada."]),
"EPSC":(["Classifica correctamente segundo a abordagem integrada.","Interpreta a curva de crescimento e o perímetro braquial.","Relaciona a idade da criança com os parâmetros de referência."],
["Executa a avaliação antropométrica e a avaliação clínica completa da criança.","Calcula e administra terapêutica pediátrica sem erro.","Executa procedimentos minimizando a dor e o medo."],
["Envolve o cuidador em todas as fases do cuidado.","Educa de forma verificável, confirmando a compreensão da instrução.","Actua em defesa da criança perante sinais de maus-tratos."]),
}
SAIDA={
"EMC":["No fim do ciclo, o formando executa a higienização das mãos e a colocação e remoção de EPI cumprindo integralmente a lista de verificação EMC-01.",
"Executa o penso de uma ferida limpa com técnica asséptica, cumprindo a lista EMC-02.",
"Monta e inicia oxigenoterapia com verificação de segurança, cumprindo a lista EMC-03.",
"Executa cateterismo vesical em simulador cumprindo a lista EMC-04.",
"Coloca sonda nasogástrica cumprindo a lista EMC-05 e regista o procedimento."],
"UEPS":["No fim do ciclo, o formando atribui prioridade a uma vítima em menos de três minutos, cumprindo a lista UEPS-01.",
"Executa a avaliação primária ABCDE em simulação, cumprindo a lista de verificação UEPS-02.",
"Executa dois minutos de Suporte Básico de Vida com aplicação de DAE, cumprindo a lista UEPS-03.",
"Controla uma hemorragia externa simulada, cumprindo a lista UEPS-04.",
"Estabiliza a coluna cervical e transfere a vítima para plano duro em equipa, cumprindo a lista UEPS-05."],
"SMON":["No fim do ciclo, o formando conduz uma consulta pré-natal completa, cumprindo a lista SMON-01.",
"Executa as manobras de Leopold e ausculta o foco fetal, cumprindo a lista SMON-02.",
"Preenche e interpreta um partograma e identifica o cruzamento da linha de acção, cumprindo a lista SMON-03.",
"Colabora na assistência a um parto normal em modelo, cumprindo a lista SMON-04.",
"Executa a reanimação neonatal básica com ventilação por máscara, cumprindo a lista SMON-05."],
"EPSC":["No fim do ciclo, o formando executa a avaliação antropométrica completa e marca-a na curva, cumprindo a lista EPSC-01.",
"Conta a frequência respiratória e classifica a pneumonia, cumprindo a lista EPSC-02.",
"Avalia o grau de desidratação e institui o plano correcto, cumprindo a lista EPSC-03.",
"Calcula uma dose por peso com dupla verificação, cumprindo a lista EPSC-04.",
"Administra uma vacina assegurando a cadeia de frio, cumprindo a lista EPSC-05."],
}
METOD={
"EMC":"O 1.º tempo lectivo abre com exposição breve e demonstração da técnica pelo formador, sempre sobre um caso clínico apresentado no início da sessão. O 2.º tempo é ocupado por treino prático supervisionado em manequim e em simulação entre pares, com correcção individual contra a lista de verificação respectiva. O bloco complementar destina-se a estudo de caso, resolução de situações clínicas, exercícios de registo e consolidação.",
"UEPS":"A disciplina privilegia a repetição deliberada. Cada manobra é demonstrada uma vez em velocidade normal e uma segunda vez decomposta em passos, sendo depois treinada em ciclos curtos e sucessivos até à automatização. As sessões de 180 minutos terminam em cenário simulado, com atribuição de funções, cronometragem e reunião de balanço estruturada. O bloco complementar destina-se a discussão de casos, verificação de material e revisão de algoritmos.",
"SMON":"As unidades de vigilância pré-natal são trabalhadas em consulta simulada, com desempenho de papéis e preenchimento efectivo do cartão e do partograma. As unidades de parto e de neonatologia decorrem em modelo obstétrico e manequim neonatal, com treino individual e em par. O bloco complementar é utilizado para interpretação de partogramas, análise de casos de mortalidade evitável e exercícios de aconselhamento.",
"EPSC":"A avaliação da criança é treinada com material antropométrico real e com registo em fichas e curvas de crescimento. Os cálculos de dose e de fluidoterapia são trabalhados em séries de exercícios corrigidos em sala, com exigência de acerto integral. Os procedimentos são executados em manequim pediátrico e em braço de punção. O bloco complementar é dedicado a estudo de casos com decisão de classificação e referência e a exercícios de educação do cuidador.",
}
MAT_DISP={
"EMC":"Cama hospitalar articulada e mesa de cabeceira; manequim de adulto para cuidados gerais; material de penso, tabuleiros e compressas; esfigmomanómetros, estetoscópios e termómetros; dispositivos de oxigenoterapia; sondas nasogástricas e vesicais; equipamento de protecção individual; contentores de resíduos por categoria; impressos do processo do doente.",
"UEPS":"Manequim de Suporte Básico de Vida para adulto; insufladores manuais e máscaras; tubos orofaríngeos; talas de imobilização e ligaduras; maca; material de penso e compressas; equipamento de protecção individual; cronómetros.",
"SMON":"Modelo pélvico obstétrico com feto e placenta; manequim neonatal; fita métrica obstétrica e estetoscópio de Pinard; esfigmomanómetro; balança neonatal; material para assistência ao parto e clampes de cordão; impressos de cartão da grávida e de partograma.",
"EPSC":"Manequim de lactente; balança pediátrica e fita métrica; fitas de perímetro braquial; curvas de crescimento impressas; seringas e agulhas; sistemas de soro; nebulizador; recipientes graduados; saquetas de sais de reidratação oral.",
}
MAT_ADQ={
"EMC":"Simulador de cateterismo vesical masculino e feminino; braço de punção venosa; oxímetro de pulso adicional; glicómetro com tiras em quantidade para treino; aspirador de secreções; kits de penso estéreis descartáveis em quantidade para execução individual por todos os formandos.",
"UEPS":"Manequins de SBV com indicador de qualidade de compressão; desfibrilhador automático externo de treino com eléctrodos reutilizáveis; colares cervicais de vários tamanhos; plano duro com imobilizadores de cabeça e cintos; torniquetes de treino; cadeira de transporte; material de simulação de feridas e hemorragia; carro de urgência para treino de verificação.",
"SMON":"Manequim neonatal com via aérea permeável; insuflador neonatal e máscaras de tamanho 0 e 1; sonicaid; tiras de pesquisa de proteinúria; amostras de métodos contraceptivos para demonstração; modelo de mama para treino de pega.",
"EPSC":"Braço e couro cabeludo de punção pediátrica; infantómetro e estadiómetro; fita de perímetro cefálico; caixa térmica com termómetro para treino de cadeia de frio; simuladores de vacina; câmaras graduadas de fluidoterapia; escalas de dor pediátricas plastificadas; dispositivos de oxigénio pediátricos.",
}
AVALP={
"EMC":"Cinco estações cronometradas de dez minutos, cada uma pontuada por lista de verificação com critérios eliminatórios de biossegurança: higienização das mãos e EPI (EMC-01); penso de ferida limpa (EMC-02); montagem e início de oxigenoterapia (EMC-03); cateterismo vesical em simulador (EMC-04); avaliação de um doente com apresentação estruturada do caso e registo escrito.",
"UEPS":"Quatro estações: dois minutos de Suporte Básico de Vida com avaliação da profundidade, cadência e relação compressão-ventilação, seguidos da aplicação do DAE (UEPS-03); controlo de hemorragia externa com aplicação de torniquete (UEPS-04); imobilização de fractura de membro e estabilização cervical com transferência para plano duro (UEPS-05); cenário integrado de vítima única com abordagem ABCDE, decisão e referência (UEPS-02). A falha em qualquer critério de segurança é eliminatória.",
"SMON":"Quatro estações: consulta pré-natal simulada com medição da altura uterina, manobras de Leopold, auscultação do foco fetal e preenchimento do cartão (SMON-01 e SMON-02); preenchimento e interpretação de um partograma com decisão de referência (SMON-03); assistência ao parto normal em modelo, incluindo dequitadura e revisão da placenta (SMON-04); cuidados imediatos ao recém-nascido e reanimação neonatal básica (SMON-05).",
"EPSC":"Quatro estações: avaliação antropométrica completa com marcação na curva e medição do perímetro braquial (EPSC-01); avaliação de criança com tosse, com contagem da frequência respiratória, pesquisa de tiragem e classificação (EPSC-02); avaliação do grau de desidratação, escolha do plano e preparação da solução de reidratação oral (EPSC-03); cálculo de dose por peso e administração em manequim com dupla verificação (EPSC-04).",
}
RESULT={
"EMC":"No fim da disciplina o formando assume um grupo de doentes adultos em internamento, organiza o turno por prioridades, executa com segurança os procedimentos do seu âmbito, aplica sistematicamente as medidas de prevenção de infecção, identifica a deterioração clínica e comunica-a em tempo útil, e deixa registos que permitem a continuidade do cuidado.",
"UEPS":"No fim da disciplina o formando aborda qualquer vítima pelo método ABCDE sem hesitação, executa Suporte Básico de Vida com qualidade verificável, opera o desfibrilhador automático externo em segurança, controla uma hemorragia externa, imobiliza e transporta uma vítima de trauma e presta os primeiros cuidados nas emergências mais frequentes, referindo correctamente.",
"SMON":"No fim da disciplina o formando conduz uma consulta pré-natal completa, preenche e interpreta um partograma, colabora na assistência a um parto normal, actua perante uma hemorragia pós-parto, executa a reanimação neonatal básica e apoia o aleitamento materno, referindo em tempo útil todas as situações que excedem a sua competência.",
"EPSC":"No fim da disciplina o formando avalia uma criança de forma completa, classifica-a correctamente segundo a abordagem integrada, decide entre tratar e referir, calcula e administra terapêutica pediátrica sem erro, executa punção venosa e fluidoterapia, administra vacinas assegurando a cadeia de frio e educa o cuidador de forma verificável.",
}
