# -*- coding: utf-8 -*-
# (tema, tipo)  tipo: T | P | TP | AV   — alinhados com o padrão L/S de core.py
EMC=[
("Âmbito de competência do Técnico de Enfermagem no cuidado ao adulto; responsabilidade profissional e segurança do doente","TP"),
("Avaliação inicial do doente adulto: colheita de dados, exame físico céfalo-caudal e identificação de sinais de alerta","TP"),
("Sinais vitais: técnica, valores de referência e interpretação de desvios (pré-requisito de Técnicas de Enfermagem)","P"),
("Registos de enfermagem: processo do doente, notas de evolução, folha terapêutica e passagem de turno estruturada","TP"),
("Infecções associadas aos cuidados de saúde: cadeia de transmissão e precauções-padrão","T"),
("Higienização das mãos, equipamento de protecção individual, isolamentos e gestão de resíduos hospitalares","TP"),
("Assepsia, desinfecção e esterilização; preparação de campo estéril e técnica de penso simples","P"),
("Feridas: classificação, fases de cicatrização e prevenção de úlceras de pressão","T"),
("Doente respiratório: pneumonia, asma e DPOC — oxigenoterapia, aerossolterapia e aspiração de secreções","TP"),
("Teste escrito 1 (Unidades I a III) e correcção comentada","AVE"),
("Doente cardiovascular: hipertensão arterial, insuficiência cardíaca e síndromes coronárias agudas — vigilância e balanço hídrico","TP"),
("Aparelho digestivo: hemorragia digestiva e hepatopatias; colocação e cuidados com sonda nasogástrica","TP"),
("Insuficiência renal, balanço hídrico e cateterismo vesical","P"),
("Diabetes mellitus: glicemia capilar, insulinoterapia e pé diabético; avaliação prática intercalar em estações","AVP"),
("Malária no adulto: sinais de gravidade, teste rápido de diagnóstico e cuidados de enfermagem","TP"),
("Tuberculose, VIH/SIDA e doença diarreica no adulto: isolamento, reidratação e adesão terapêutica","TP"),
("Choque no adulto: reconhecimento, posicionamento, fluidoterapia e vigilância","TP"),
("Teste escrito 2 (Unidades IV a VI) e correcção comentada","AVE"),
("Enfermagem perioperatória: preparação pré-operatória, lista de verificação de segurança cirúrgica e cuidados pós-operatórios","TP"),
("Complicações pós-operatórias: deiscência, infecção do local cirúrgico e prevenção de tromboembolismo","T"),
("Caso integrado: adulto com malária grave e desidratação — articulação com UEPS","P"),
("Caso integrado: adulto politraumatizado em internamento — articulação com UEPS","P"),
("Caso integrado: doente crónico com hipertensão e diabetes — continuidade de cuidados e referência","TP"),
("Revisão integrada das Unidades I a IV com resolução de situações clínicas","TP"),
("Revisão integrada das Unidades V a VII e preparação da avaliação final","T"),
("Avaliação prática final em estações: penso, oxigenoterapia, cateterismo vesical, sonda nasogástrica e avaliação do doente","AVP"),
("Avaliação final teórico-prática — componente escrita — e devolução dos resultados","AVE")]

UEPS=[
("O serviço de urgência: organização, fluxos e âmbito de actuação do Técnico de Enfermagem","T"),
("Triagem e classificação de risco: critérios de prioridade e sinais de alarme","T"),
("Abordagem primária ABCDE: método, sequência, reavaliação e treino em cenário simulado","P"),
("Registo do episódio de urgência e comunicação estruturada com a equipa","TP"),
("Permeabilização da via aérea, posição lateral de segurança, aspiração e tubo orofaríngeo","P"),
("Ventilação com insuflador manual e máscara: técnica, selagem e erros mais frequentes","P"),
("Paragem cardiorrespiratória: reconhecimento e cadeia de sobrevivência","T"),
("Suporte Básico de Vida no adulto com desfibrilhador automático externo: treino intensivo em manequim","P"),
("Hemorragia externa: compressão directa, penso compressivo e torniquete","P"),
("Choque: reconhecimento precoce, posicionamento e fluidoterapia inicial; punção venosa periférica em urgência","TP"),
("Teste escrito 1 (Unidades I a III) e correcção comentada","AVE"),
("Avaliação primária e secundária da vítima de trauma; traumatismos por acidente de viação","TP"),
("Imobilização de fracturas com talas e ligaduras; estabilização cervical e rolamento em bloco; avaliação prática intercalar","AVP"),
("Mobilização e transporte de vítimas: maca, plano duro e transferência segura","P"),
("Queimaduras: avaliação da extensão e profundidade, arrefecimento, penso e reposição de fluidos","TP"),
("Intoxicações, mordeduras de serpente e picadas: conduta inicial e profilaxia do tétano e da raiva","T"),
("Convulsão e estado de mal convulsivo; alteração do estado de consciência","TP"),
("Malária grave e desidratação grave em contexto de urgência; hipoglicemia e cetoacidose","TP"),
("Teste escrito 2 (Unidades IV a VI) e correcção comentada","AVE"),
("Anafilaxia, crise asmática e insuficiência respiratória aguda: reconhecimento e actuação imediata","TP"),
("Princípios de triagem em situação de multivítimas","T"),
("Carro de urgência: composição, verificação diária, reposição e responsabilidade","TP"),
("Simulação integrada: cenário de multivítimas com triagem, estabilização e referência","P"),
("Revisão dos algoritmos de suporte básico de vida e de abordagem ao trauma","T"),
("Treino final de SBV com DAE e de imobilização, com correcção individual contra lista de verificação","P"),
("Revisão integrada e preparação da avaliação final","T"),
("Avaliação prática final em estações: SBV com DAE, hemorragia, imobilização e cenário ABCDE","AVP")]

SMON=[
("Saúde sexual e reprodutiva: conceitos, direitos da mulher, ética e âmbito de actuação do Técnico de Enfermagem","TP"),
("Anatomofisiologia aplicada do aparelho reprodutor feminino e ciclo menstrual (pré-requisito de Anatomia)","T"),
("Planeamento familiar: métodos contraceptivos, aconselhamento, técnica de administração e seguimento","TP"),
("Diagnóstico de gravidez, modificações fisiológicas e cálculo da idade gestacional e da data provável do parto","TP"),
("Consulta pré-natal: calendário, exames de rotina e preenchimento do cartão da grávida","TP"),
("Nutrição, suplementação com ferro e ácido fólico, vacinação antitetânica e educação para a saúde na gravidez","T"),
("Vigilância pré-natal prática: altura uterina, manobras de Leopold e auscultação do foco fetal","P"),
("Anemia na gravidez: rastreio, prevenção e cuidados de enfermagem","T"),
("Malária na gravidez: tratamento preventivo intermitente, rede mosquiteira e vigilância","TP"),
("Teste escrito 1 (Unidades I a III) e correcção comentada","AVE"),
("Sífilis e prevenção da transmissão vertical do VIH e da hepatite B: aconselhamento, testagem e seguimento","TP"),
("Trabalho de parto: fisiologia, períodos, mecanismo do parto e admissão da parturiente","T"),
("Partograma: preenchimento, linha de alerta e linha de acção; avaliação prática intercalar","AVP"),
("Preparação do material e do campo para o parto; apoio e posições da parturiente","P"),
("Assistência ao parto normal em modelo: protecção do períneo e clampagem do cordão (simulação; em contexto real apenas sob supervisão)","P"),
("Terceiro período: manejo activo da dequitadura e revisão da placenta","TP"),
("Pré-eclâmpsia e eclâmpsia: pesquisa de proteinúria, vigilância e conduta de emergência","TP"),
("Teste escrito 2 (Unidades IV a VI) e correcção comentada","AVE"),
("Hemorragia pós-parto e sépsis materna: massagem uterina, compressão bimanual e uterotónicos sob supervisão","P"),
("Cuidados imediatos ao recém-nascido: secagem, contacto pele a pele e índice de Apgar","TP"),
("Reanimação neonatal básica: passos iniciais e ventilação com máscara — treino em manequim","P"),
("Aleitamento materno: fisiologia da lactação, pega correcta e dificuldades comuns","TP"),
("Sépsis neonatal, icterícia e recém-nascido de baixo peso: sinais de perigo, método canguru e referência","TP"),
("Revisão integrada das Unidades I a IV com interpretação de partogramas","TP"),
("Revisão integrada das Unidades V a VII com simulação de emergência obstétrica","P"),
("Preparação da avaliação final e esclarecimento de dúvidas","T"),
("Avaliação final em estações: consulta pré-natal, partograma, parto em modelo e reanimação neonatal","AVP")]

EPSC=[
("Princípios da enfermagem pediátrica, direitos da criança e comunicação com a criança e a família","T"),
("Crescimento e desenvolvimento: marcos, curvas de crescimento e avaliação antropométrica","TP"),
("Sinais vitais pediátricos por faixa etária e sinais gerais de perigo","P"),
("Aleitamento exclusivo, diversificação alimentar e erros alimentares frequentes","TP"),
("Rastreio da malnutrição aguda: perímetro braquial e pesquisa de edema bilateral","P"),
("Classificação e cuidados na malnutrição aguda grave e moderada; alimentos terapêuticos prontos a usar","TP"),
("Educação nutricional da família e vigilância do ganho ponderal","T"),
("Abordagem integrada das doenças da infância: avaliar, classificar, tratar e referir","TP"),
("Teste escrito 1 (Unidades I a III) e correcção comentada","AVE"),
("Programa Alargado de Vacinação: calendário, cadeia de frio e técnica de administração de vacinas","P"),
("Registo vacinal, eventos adversos pós-vacinação e recuperação de faltosos","T"),
("Avaliação do grau de desidratação e planos de tratamento A, B e C; avaliação prática intercalar","AVP"),
("Terapia de reidratação oral: preparação da solução e educação do cuidador","P"),
("Pneumonia: contagem da frequência respiratória, tiragem, classificação e cuidados de enfermagem","TP"),
("Bronquiolite, asma e laringite: nebulização e oxigenoterapia pediátrica","P"),
("Malária na criança e malária grave: sinais de gravidade, teste rápido e cuidados de enfermagem","TP"),
("Drepanocitose: crise vaso-oclusiva, hidratação, controlo da dor e prevenção de complicações","TP"),
("Febre na criança e convulsão febril; doenças exantemáticas e medidas de isolamento","TP"),
("Teste escrito 2 (Unidades IV a VI) e correcção comentada","AVE"),
("Cálculo de doses por peso e dupla verificação; administração por via oral, intramuscular e endovenosa","P"),
("Punção venosa periférica pediátrica e fluidoterapia: cálculo do ritmo de gotejo","P"),
("Caso integrado: criança com malária grave e desidratação — articulação com SMON e UEPS","P"),
("Avaliação e controlo da dor na criança; sinais de maus-tratos e dever de comunicação","TP"),
("Revisão integrada das Unidades I a IV com estudo de casos de abordagem integrada","TP"),
("Revisão integrada das Unidades V a VII e preparação da avaliação final","T"),
("Avaliação final prática em estações: antropometria, classificação de pneumonia, desidratação e cálculo de dose","AVP"),
("Avaliação final teórico-prática — componente escrita — e devolução dos resultados","AVE")]
