# -*- coding: utf-8 -*-
"""Conteúdos autorais do Programa de Formação Técnico-Profissional em Enfermagem — MIDAS 26."""

# Cada lista está alinhada com o padrão de blocos gerado em sched.py:
# L = 180 min (1.º + 2.º tempo)  ·  S = 60 min (bloco complementar)
# natureza: T = teórica · TP = teórico-prática · P = prática · AV = avaliação

EMC = [
 ("Abertura do ciclo: âmbito de competência do Técnico de Enfermagem no cuidado ao adulto, responsabilidade profissional e segurança do doente","TP","I"),
 ("Registos de enfermagem: processo do doente, notas de evolução, folha terapêutica e passagem de turno","T","I"),
 ("Admissão e avaliação inicial do adulto: colheita de dados, exame físico céfalo-caudal e sinais de alerta precoce","TP","I"),
 ("Infeções associadas aos cuidados de saúde: cadeia de transmissão, precauções-padrão e higienização das mãos","T","II"),
 ("Equipamento de proteção individual, isolamentos, gestão de resíduos hospitalares e biossegurança do profissional","TP","II"),
 ("Assepsia, desinfeção e esterilização: preparação do campo estéril e manuseamento de material crítico","TP","II"),
 ("Feridas: classificação, fases de cicatrização e critérios de avaliação","T","II"),
 ("Técnica de penso: penso simples, penso húmido, cuidados a drenagens e remoção de suturas","P","II"),
 ("Úlceras de pressão: escalas de risco, prevenção, posicionamentos terapêuticos e superfícies de apoio","TP","II"),
 ("Enfermagem cardiovascular: hipertensão arterial e insuficiência cardíaca — vigilância, balanço hídrico e educação do doente","TP","III"),
 ("Síndromes coronárias agudas: reconhecimento, cuidados imediatos e preparação da transferência","TP","III"),
 ("1.ª Avaliação escrita da disciplina (Unidades I a III) e correção comentada","AV","III"),
 ("Enfermagem respiratória: DPOC, asma e pneumonia — posicionamento, cinesiterapia respiratória e vigilância","TP","III"),
 ("Aspiração de secreções e colheita de expetoração: técnica, biossegurança e registo","P","III"),
 ("Oxigenoterapia e aerossolterapia: dispositivos, débitos, humidificação, riscos e segurança","TP","III"),
 ("Aparelho digestivo: hepatopatias, ascite e hemorragia digestiva — colocação e cuidados com sonda nasogástrica","TP","IV"),
 ("Alimentação entérica e apoio nutricional ao doente internado: preparação, administração e vigilância","TP","IV"),
 ("Enfermagem renal e urológica: insuficiência renal, balanço hídrico e cateterismo vesical","TP","IV"),
 ("Diabetes mellitus: glicemia capilar, insulinoterapia, conservação da insulina e educação do doente","TP","IV"),
 ("Pé diabético: avaliação do risco, técnica de penso, descarga e prevenção da amputação","TP","IV"),
 ("Enfermagem neurológica: acidente vascular cerebral — avaliação, disfagia, posicionamento e reabilitação precoce","TP","IV"),
 ("Doente inconsciente e acamado: higiene, mobilização, prevenção de complicações e cuidados à família","P","IV"),
 ("Enfermagem perioperatória: preparação pré-operatória, lista de verificação de segurança cirúrgica e circuitos do bloco operatório","TP","V"),
 ("Cuidados pós-operatórios imediatos: vigilância hemodinâmica, controlo da dor, drenos e complicações precoces","TP","V"),
 ("Doenças infeciosas prevalentes (malária grave, tuberculose, VIH/SIDA e cólera): isolamento, reidratação e adesão terapêutica","TP","VI"),
 ("Avaliação prática final em estações de competência: penso, oxigenoterapia, cateterismo vesical, sonda nasogástrica e avaliação do doente","AV","VII"),
 ("Encerramento: 2.ª avaliação escrita (Unidades IV a VI), revisão global e devolução dos resultados","AV","VII"),
]

UEPS = [
 ("O serviço de urgência: organização, fluxos, âmbito de atuação do Técnico de Enfermagem e cadeia de sobrevivência","T","I"),
 ("Abordagem sistemática ABCDE: método, sequência, reavaliação e treino em cenário simulado","TP","I"),
 ("Triagem e classificação de risco: critérios de prioridade, sinais de alarme e registo do episódio","T","I"),
 ("Via aérea: permeabilização, posição lateral de segurança, aspiração e adjuvantes (tubo orofaríngeo)","TP","I"),
 ("Paragem cardiorrespiratória: reconhecimento, ativação do socorro e princípios de reanimação","T","II"),
 ("Ventilação com insuflador manual e máscara: técnica, selagem e erros mais frequentes","P","II"),
 ("Suporte Básico de Vida no adulto: treino intensivo em manequim — compressões, ventilações e ciclos","P","II"),
 ("Desfibrilhação automática externa: indicações, sequência operacional e regras de segurança","TP","II"),
 ("Suporte Básico de Vida pediátrico e no lactente e desobstrução da via aérea por corpo estranho: treino integrado","P","II"),
 ("Acesso venoso periférico em contexto de urgência: escolha do cateter, técnica, fixação e complicações","P","III"),
 ("Choque: tipos, reconhecimento precoce, posicionamento e fluidoterapia inicial","T","III"),
 ("Hemorragias: compressão direta, penso compressivo, torniquete e controlo de hemorragia externa — treino","P","IV"),
 ("Anafilaxia e reações alérgicas graves: reconhecimento, atuação imediata e vigilância","TP","III"),
 ("Traumatismos osteoarticulares: entorses, luxações e fraturas — imobilização com talas e ligaduras","P","IV"),
 ("Traumatismo craniencefálico: avaliação do estado de consciência e prevenção da lesão secundária","T","IV"),
 ("Avaliação primária e secundária da vítima de trauma: método, exame rápido e registo","TP","IV"),
 ("Trauma da coluna vertebral: estabilização cervical, rolamento em bloco e transferência para plano duro","P","IV"),
 ("1.ª Avaliação escrita da disciplina (Unidades I a III) e correção comentada","AV","III"),
 ("Mobilização e transporte de vítimas: técnicas de levantamento, maca, cadeira de transporte e transferência segura","P","IV"),
 ("Emergências neurológicas: convulsões, estado de mal convulsivo e alteração do estado de consciência","TP","III"),
 ("Emergências metabólicas: hipoglicemia, cetoacidose diabética e desidratação grave","TP","III"),
 ("Queimaduras: avaliação da extensão e profundidade, arrefecimento, penso e reposição de fluidos","TP","V"),
 ("Intoxicações e envenenamentos: vias de exposição, descontaminação, conduta e prevenção","T","V"),
 ("Mordeduras e picadas (serpentes, escorpiões e cães), afogamento e choque elétrico: conduta e profilaxia do tétano e da raiva","TP","V"),
 ("Carro de urgência e material de emergência: composição, verificação diária, reposição e responsabilidade","TP","VI"),
 ("Emergências com multivítimas: princípios de triagem em catástrofe e organização do local","T","VI"),
 ("Simulação integrada final e avaliação prática de competências de emergência em estações","AV","VI"),
]

SMON = [
 ("Saúde sexual e reprodutiva: conceitos, direitos da mulher, ética e âmbito de atuação do Técnico de Enfermagem","TP","I"),
 ("Anatomofisiologia aplicada do aparelho reprodutor feminino e ciclo menstrual","T","I"),
 ("Planeamento familiar: métodos contracetivos, aconselhamento, técnica de administração e seguimento","TP","I"),
 ("Infeções de transmissão sexual: rastreio, aconselhamento, tratamento do parceiro e prevenção","T","I"),
 ("Diagnóstico de gravidez, modificações fisiológicas maternas e cálculo da idade gestacional e da data provável do parto","TP","II"),
 ("Consulta pré-natal: calendário, primeira consulta, exames de rotina e preenchimento do cartão da grávida","TP","II"),
 ("Nutrição, suplementação com ferro e ácido fólico, vacinação antitetânica e educação para a saúde na gravidez","T","II"),
 ("Vigilância pré-natal prática: altura uterina, manobras de Leopold, auscultação do foco fetal e avaliação do bem-estar fetal","P","II"),
 ("Anemia e malária na gravidez: prevenção, rastreio, tratamento preventivo intermitente e cuidados de enfermagem","TP","III"),
 ("Doenças hipertensivas da gravidez: pré-eclâmpsia e eclâmpsia — vigilância, pesquisa de proteinúria e conduta de emergência","TP","III"),
 ("Hemorragias da gravidez: aborto, gravidez ectópica, placenta prévia e descolamento — reconhecimento e encaminhamento","TP","III"),
 ("1.ª Avaliação escrita da disciplina (Unidades I a III) e correção comentada","AV","III"),
 ("Prevenção da transmissão vertical do VIH, sífilis e hepatite B: aconselhamento, testagem, adesão e seguimento","TP","III"),
 ("Trabalho de parto: fisiologia, períodos, mecanismo do parto e admissão da parturiente","T","IV"),
 ("Partograma: preenchimento, interpretação da linha de alerta e da linha de ação e tomada de decisão","TP","IV"),
 ("Assistência ao parto normal: preparação do material, campo estéril, proteção do períneo e clampagem do cordão","TP","IV"),
 ("Terceiro período e dequitadura: manejo ativo, revisão da placenta e avaliação de lacerações","TP","IV"),
 ("Simulação de parto normal em modelo: treino integrado de manobras, posições, apoio à parturiente e registo","P","IV"),
 ("Aleitamento materno: fisiologia da lactação, pega correta, dificuldades comuns e aconselhamento","TP","VI"),
 ("Hemorragia pós-parto: causas, massagem uterina, uterotónicos e compressão bimanual — treino em modelo","P","V"),
 ("Emergências obstétricas: distócia de ombros, prolapso do cordão e apresentações anómalas — reconhecimento e conduta","TP","V"),
 ("Puerpério normal e patológico: involução uterina, lóquios, infeção puerperal e sinais de alerta","TP","V"),
 ("Cuidados imediatos ao recém-nascido e reanimação neonatal básica: índice de Apgar, passos iniciais e ventilação com máscara","P","VI"),
 ("Recém-nascido de baixo peso e prematuro: termorregulação, método canguru e icterícia neonatal","TP","VI"),
 ("Sépsis neonatal e sinais de perigo; avaliação prática final em estações (pré-natal, partograma, parto e reanimação neonatal)","AV","VI"),
 ("Encerramento: 2.ª avaliação escrita (Unidades IV a VI), revisão global e devolução dos resultados","AV","VI"),
]

EPSC = [
 ("Enfermagem pediátrica: princípios, direitos da criança, cuidados centrados na família e comunicação com a criança","T","I"),
 ("Crescimento e desenvolvimento infantil: marcos, curvas de crescimento e avaliação antropométrica (peso, comprimento e perímetro cefálico)","TP","I"),
 ("Particularidades anatomofisiológicas da criança e implicações para os cuidados de enfermagem","T","I"),
 ("Avaliação clínica da criança: sinais vitais por faixa etária, exame físico e sinais gerais de perigo","TP","I"),
 ("Abordagem integrada das doenças da infância: classificação, decisão e critérios de encaminhamento","T","I"),
 ("Alimentação do lactente e da criança: aleitamento exclusivo, diversificação alimentar e erros frequentes","T","II"),
 ("Desnutrição aguda: rastreio com perímetro braquial e pesquisa de edema, classificação e cuidados de enfermagem","TP","II"),
 ("Reabilitação nutricional: alimentos terapêuticos prontos a usar, vigilância do ganho ponderal e educação da família","TP","II"),
 ("Programa Alargado de Vacinação: calendário, conservação, cadeia de frio e técnica de administração de vacinas","TP","III"),
 ("Registo vacinal, vigilância de eventos adversos pós-vacinação e recuperação de faltosos","T","III"),
 ("Doenças respiratórias da infância: pneumonia — contagem da frequência respiratória, tiragem e classificação","TP","IV"),
 ("Bronquiolite, asma e laringite: oxigenoterapia e nebulização pediátrica — demonstração e treino","P","IV"),
 ("1.ª Avaliação escrita da disciplina (Unidades I a III) e correção comentada","AV","III"),
 ("Doença diarreica: avaliação do grau de desidratação e planos de tratamento A, B e C","TP","IV"),
 ("Terapia de reidratação oral: preparação da solução, administração e educação da mãe ou cuidador","P","IV"),
 ("Malária na criança: sinais de gravidade, teste rápido de diagnóstico e cuidados de enfermagem","TP","IV"),
 ("Febre na criança e doenças exantemáticas (sarampo, varicela e tosse convulsa): abordagem, medidas físicas e isolamento","TP","IV"),
 ("Cálculo de doses pediátricas por peso: exercícios práticos e regra da dupla verificação","P","V"),
 ("Administração de medicamentos na criança: via oral, intramuscular e endovenosa — técnica e segurança","P","V"),
 ("Punção venosa periférica em pediatria: escolha do local, técnica, fixação e complicações","P","V"),
 ("Fluidoterapia pediátrica: cálculo de necessidades, ritmo de gotejo e vigilância da perfusão","TP","V"),
 ("Colheita de amostras e procedimentos frequentes em pediatria: técnica, imobilização segura e conforto","P","V"),
 ("Avaliação e controlo da dor na criança: escalas por idade e medidas não farmacológicas","TP","VI"),
 ("Emergências pediátricas frequentes: convulsão febril, desidratação grave e dificuldade respiratória — simulação","P","VI"),
 ("Criança hospitalizada e proteção da criança: acolhimento, brincar terapêutico, sinais de maus-tratos e dever de comunicação","TP","VI"),
 ("Avaliação prática final em estações e encerramento: 2.ª avaliação escrita, revisão global e devolução dos resultados","AV","VI"),
]

SEMINARIOS = [
 ("Língua Portuguesa","Comunicação escrita e registos de enfermagem: clareza, rigor e terminologia técnica",
  ["Ortografia e construção frásica aplicadas ao registo clínico","Terminologia técnica de enfermagem e abreviaturas aceites","Redação de notas de evolução: o que se escreve e o que nunca se escreve","Oficina: correção de registos reais anonimizados"]),
 ("Psicologia","Relação de ajuda e comunicação terapêutica com o doente e a família",
  ["Escuta ativa, empatia e presença profissional","Comunicação de informação difícil e gestão de reações emocionais","Barreiras culturais e linguísticas na relação de cuidado","Oficina: dramatização de situações de acolhimento"]),
 ("Saúde Coletiva","Sistema de saúde, cuidados primários e níveis de atenção",
  ["Organização dos níveis de atenção e circuito de referência do doente","Cuidados de saúde primários e o papel do Técnico de Enfermagem na comunidade","Determinantes sociais da saúde no contexto angolano","Oficina: mapeamento do percurso do doente da comunidade ao hospital"]),
 ("Saúde Mental","Noções fundamentais de saúde mental e primeiros cuidados psicológicos",
  ["Saúde mental, sofrimento psíquico e desmistificação do estigma","Reconhecimento de sinais de ansiedade, depressão e psicose","Primeiros cuidados psicológicos e contenção verbal","Oficina: abordagem do doente em sofrimento no serviço"]),
 ("Língua Portuguesa","Relatório de enfermagem, passagem de turno e comunicação oral profissional",
  ["Estrutura do relatório de enfermagem e do relatório de ocorrência","Passagem de turno estruturada: método e concisão","Comunicação oral com a equipa e com o médico: reportar o essencial","Oficina: simulação de passagem de turno avaliada"]),
 ("Psicologia","Stress ocupacional, luto, burnout e autocuidado do profissional de saúde",
  ["Stress, fadiga por compaixão e sinais de esgotamento profissional","Acompanhamento do doente e da família em processo de luto","Trabalho em equipa e gestão de conflitos no serviço","Oficina: plano pessoal de autocuidado"]),
 ("Saúde Mental","Urgências em saúde mental: agitação, risco de suicídio, álcool e outras drogas",
  ["Abordagem do doente agitado: segurança do doente e do profissional","Avaliação e encaminhamento do risco de suicídio","Intoxicação alcoólica, síndrome de privação e consumo de substâncias","Oficina: estudo de casos e decisão de encaminhamento"]),
 ("Saúde Coletiva","Epidemiologia, vigilância e educação para a saúde na comunidade",
  ["Noções de epidemiologia: incidência, prevalência e surto","Vigilância epidemiológica e notificação de doenças","Planeamento de uma ação de educação para a saúde","Oficina: conceção e apresentação de uma sessão comunitária"]),
]
print("EMC",len(EMC),"UEPS",len(UEPS),"SMON",len(SMON),"EPSC",len(EPSC),"SEM",len(SEMINARIOS))
